# Training configuration for retail forecasting

# environment configuration
settings:
  docker:
    required_integrations:
      - pandas
      - numpy
    requirements:
      - matplotlib>=3.5.0
      - plotly
      - prophet>=3.5.0
      - pyarrow
      - fastparquet
      - typing_extensions>=4.0.0

# configuration of the Model Control Plane
model:
  name: retail_forecast_model
  version: 0.1.0
  license: MIT
  description: A retail forecast model with enhanced seasonality
  tags: ["retail", "forecasting", "prophet", "seasonal"]

# Step-specific parameters
steps:
  # Data loading parameters
  load_data: {}
  
  # Data preprocessing parameters
  preprocess_data:
    parameters:
      test_size: 0.2
      min_train_size: 50
      outlier_threshold: 3.0
      enable_feature_engineering: true
  
  # Model training parameters
  train_model:
    parameters:
      # Seasonality settings optimized for limited data
      weekly_seasonality: true
      yearly_seasonality: false  # Disabled due to insufficient data (90 days)
      daily_seasonality: false   # Not useful for daily retail data
      seasonality_mode: "multiplicative"
      
      # Regularization and constraints
      changepoint_prior_scale: 0.05  # Reduced flexibility to prevent overfitting
      seasonality_prior_scale: 1.0
      holidays_prior_scale: 10.0  # Strength of holiday effects
      growth: "linear"
      
      # Additional Prophet parameters for better performance
      interval_width: 0.95
      mcmc_samples: 0  # Disable MCMC for faster training
      
      # Custom parameters for retail forecasting
      cap: null  # Will be set dynamically based on data
      floor: 0   # Sales cannot be negative
      use_regressors: true  # Enable weekend, promo, and other regressors
  
  # Forecasting parameters
  generate_forecasts:
    parameters:
      forecast_periods: 60 
